name: CI

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bun install
      - name: Check formatting with Biome
        run: bun run format-check
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bun install
      - name: Check linting with Biome
        run: bun run lint-check
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bun install
      - name: Build with Typescript
        run: bun run build